name: Flutter CI

on:
  push:
    branches:
      - main
    paths:
      - "cortexai_app/**"
      - ".github/workflows/flutter.yml"

  pull_request:
    branches:
      - main
    paths:
      - "cortexai_app/**"
      - ".github/workflows/flutter.yml"

jobs:
  flutter:
    name: Flutter Analyze & Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cortexai_app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --release
