name: Markdown Lint

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - ".github/workflows/markdown-lint.yml"

  pull_request:
    branches:
      - main
    paths:
      - "**/*.md"
      - ".github/workflows/markdown-lint.yml"

jobs:
  markdown-lint:
    name: Lint Markdown
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint markdown files
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: "**/*.md"
